function init(self)
	msg.post(".", "acquire_input_focus")
	self.move_distance = 0
	self.paddle_speed = 750 
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	local pos = go.get_position() 
	pos.x = pos.x + self.move_distance * dt

	-- Prevent the paddle leaving the screen
	if pos.x<-400 then
		pos.x = -400
	end
	if pos.x>400 then
		pos.x = 400
	end
	--

	go.set_position(pos) 
	self.move_distance = 0
end

function fixed_update(self, dt)
	-- This function is only called if 'Use Fixed Timestep' is enabled in the Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == hash("player3_right") then
		self.move_distance = self.paddle_speed
	end
	if action_id == hash("player3_left") then
		self.move_distance = -self.paddle_speed
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
