function init(self)
	self.player1_score = 0
	self.player2_score = 0
	self.player3_score = 0
	self.player4_score = 0
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is only called if 'Use Fixed Timestep' is enabled in the Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("player1_scored") then
		self.player1_score = self.player1_score + 1
		label.set_text("#label", self.player1_score .. " : " .. self.player2_score.. " : " ..self.player3_score .. " : " .. self.player4_score)
	end
	if message_id == hash("player2_scored") then
		self.player2_score = self.player2_score + 1
		label.set_text("#label", self.player1_score .. " : " .. self.player2_score.. " : " ..self.player3_score .. " : " .. self.player4_score)
		end
	if message_id == hash("player3_scored") then
		self.player3_score = self.player3_score + 1
		label.set_text("#label", self.player1_score .. " : " .. self.player2_score.. " : " ..self.player3_score .. " : " .. self.player4_score)
		end
	if message_id == hash("player4_scored") then
		self.player4_score = self.player4_score + 1
		label.set_text("#label", self.player1_score .. " : " .. self.player2_score.. " : " ..self.player3_score .. " : " .. self.player4_score)
		end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
